---
openapi: '3.0.2'

info:
  title: dynv6 zone and records update api
  version: '1.0'
  contact:
    email: kontakt@digineo.de

tags:
  - name: records
  - name: zones

paths:
  /zones:
    $ref: './paths/zones.yml#/Zones'

  /zones/{id}:
    $ref: './paths/zone.yml#/ZoneByID'

  /zones/by-name/{name}:
    $ref: './paths/zone.yml#/ZoneByName'

  /zones/{zoneID}/records:
    $ref: './paths/records.yml#/Records'

  /zones/{zoneID}/records/{recordID}:
    $ref: './paths/record.yml#/Record'

components:
  schemas:
    Zone:
      $ref: './models/zone.yml#/Zone'
    Record:
      $ref: './models/record.yml#/Record'

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
